#pragma once
#include "raylib.h"
#include "header/note/note.h"
#include <vector>

struct ScheduleNote
{
    float time;
    NoteType type;
    Shipping shipping;
    Color color = BLUE;
    Vector2 size = {50, 50};
    bool spawned = false;
};

std::vector<ScheduleNote> baseNoteSchedule = {
    {6.1f, TAP, Shipping::LEFT, RED},
    {6.5f, TAP, Shipping::RIGHT, RED},
    {7.0f, TAP, Shipping::LEFT, WHITE},
    {8.26f, TAP, Shipping::RIGHT, WHITE},
    {8.6f, TAP, Shipping::LEFT, BLUE},
    {9.23f, TAP, Shipping::RIGHT, BLUE},
    {9.65f, TAP, Shipping::LEFT, WHITE},
    {10.0f, TAP, Shipping::RIGHT, WHITE},
    {10.7f, TAP, Shipping::LEFT, WHITE},
    {11.3f, HOLD, Shipping::RIGHT, WHITE, {400, 50}},
    {11.75f, TAP, Shipping::LEFT, WHITE},
    {12.59f, TAP, Shipping::LEFT, WHITE},
    {13.43f, HOLD, Shipping::LEFT, WHITE, {400, 50}},
    {14.28f, TAP, Shipping::RIGHT, WHITE},
    {14.7f, TAP, Shipping::RIGHT, WHITE},
    {15.1f, TAP, Shipping::RIGHT, WHITE},
    {15.75f, TAP, Shipping::RIGHT, WHITE},
    {15.96f, TAP, Shipping::LEFT, WHITE},
    {16.8f, HOLD, Shipping::LEFT, WHITE, {400, 50}},
    {17.65f, TAP, Shipping::RIGHT, WHITE},
    {18.0f, TAP, Shipping::RIGHT, WHITE},
    {18.91f, TAP, Shipping::RIGHT, WHITE},
    {19.34f, TAP, Shipping::LEFT, WHITE},
    {20.17f, TAP, Shipping::RIGHT, WHITE},
    {21.01f, TAP, Shipping::LEFT, WHITE},
    {21.43f, TAP, Shipping::RIGHT, WHITE},
    {21.8f, TAP, Shipping::LEFT, WHITE},
    {22.4f, HOLD, Shipping::RIGHT, WHITE, {400, 50}},
    {22.7f, TAP, Shipping::LEFT, WHITE},
    {23.54f, TAP, Shipping::LEFT, WHITE},
    {24.38f, TAP, Shipping::LEFT, WHITE},
    {24.8f, TAP, Shipping::RIGHT, WHITE},
    {25.48f, HOLD, Shipping::RIGHT, WHITE, {400, 50}},
    {25.6f, TAP, Shipping::LEFT, WHITE},
    {26.06f, TAP, Shipping::LEFT, WHITE},
    {26.9f, TAP, Shipping::LEFT, WHITE},
    {27.32f, TAP, Shipping::RIGHT, WHITE},
    {27.74f, TAP, Shipping::RIGHT, WHITE},
    {28.59f, TAP, Shipping::LEFT, WHITE},
    {29.01f, TAP, Shipping::RIGHT, WHITE},
    {29.43f, TAP, Shipping::LEFT, WHITE},
    {30.27f, HOLD, Shipping::LEFT, WHITE, {400, 50}},
    {30.69f, TAP, Shipping::RIGHT, WHITE},
    {31.11f, TAP, Shipping::RIGHT, WHITE},
    {31.95f, TAP, Shipping::RIGHT, WHITE},
    {32.3f, TAP, Shipping::RIGHT, WHITE},
    {32.8f, TAP, Shipping::LEFT, WHITE},
    {33.6f, HOLD, Shipping::RIGHT, WHITE, {400, 50}},
    {34.06f, TAP, Shipping::LEFT, WHITE},
    {34.48f, TAP, Shipping::LEFT, WHITE},
    {35.32f, TAP, Shipping::LEFT, WHITE},
    {35.74f, TAP, Shipping::RIGHT, WHITE},
    {36.16f, TAP, Shipping::LEFT, WHITE},
    {36.16f, TAP, Shipping::RIGHT, WHITE},
    {37.0f, HOLD, Shipping::LEFT, WHITE, {400, 50}},
    {37.8f, TAP, Shipping::RIGHT, WHITE},
    {38.27f, TAP, Shipping::RIGHT, WHITE},
    {38.6f, TAP, Shipping::RIGHT, WHITE},
    {39.53f, TAP, Shipping::LEFT, WHITE},
    {40.8f, HOLD, Shipping::RIGHT, WHITE, {400, 50}},
    {41.22f, TAP, Shipping::LEFT, WHITE},
    {42.05f, TAP, Shipping::LEFT, WHITE},
    {42.48f, TAP, Shipping::LEFT, WHITE},
    {42.92f, TAP, Shipping::RIGHT, WHITE},
    {42.92f, TAP, Shipping::LEFT, WHITE},
    {43.7f, TAP, Shipping::RIGHT, WHITE},
    {44.58f, TAP, Shipping::LEFT, WHITE},
    {45.0f, HOLD, Shipping::LEFT, WHITE, {400, 50}},
    {45.42f, TAP, Shipping::RIGHT, WHITE},
    {45.8f, TAP, Shipping::RIGHT, WHITE},
    {46.26f, TAP, Shipping::RIGHT, WHITE},
    {47.1f, TAP, Shipping::RIGHT, WHITE},
    {47.53f, TAP, Shipping::LEFT, WHITE},
    {47.95f, TAP, Shipping::LEFT, WHITE},
    {48.37f, TAP, Shipping::RIGHT, WHITE},
    {49.2f, HOLD, Shipping::RIGHT, WHITE, {400, 50}},
    {49.62f, TAP, Shipping::LEFT, WHITE},
    {50.04f, TAP, Shipping::LEFT, WHITE},
    {50.88f, TAP, Shipping::LEFT, WHITE},
    {51.3f, TAP, Shipping::LEFT, WHITE},
    {52.0f, HOLD, Shipping::LEFT, WHITE, {400, 50}},
    {52.42f, TAP, Shipping::RIGHT, WHITE},
    {53.25f, TAP, Shipping::RIGHT, WHITE},
    {53.67f, TAP, Shipping::RIGHT, WHITE},
    {54.1f, TAP, Shipping::LEFT, WHITE},
    {54.88f, HOLD, Shipping::RIGHT, WHITE, {400, 50}},
    {54.88f, HOLD, Shipping::LEFT, WHITE, {400, 50}},
    {56.97f, TAP, Shipping::RIGHT, WHITE},
    {56.97f, TAP, Shipping::LEFT, WHITE},
    {57.8f, HOLD, Shipping::RIGHT, WHITE, {400, 50}},
    {58.22f, TAP, Shipping::LEFT, WHITE},
    {59.05f, TAP, Shipping::LEFT, WHITE},
    {59.47f, TAP, Shipping::RIGHT, WHITE},
    {59.89f, TAP, Shipping::LEFT, WHITE},
    {60.67f, HOLD, Shipping::RIGHT, WHITE, {400, 50}},
    {61.09f, TAP, Shipping::LEFT, WHITE},
    {61.51f, TAP, Shipping::LEFT, WHITE},
    {62.35f, TAP, Shipping::LEFT, WHITE},
    {62.77f, TAP, Shipping::RIGHT, WHITE},
    {63.6f, HOLD, Shipping::LEFT, WHITE, {400, 50}},
    {64.02f, TAP, Shipping::RIGHT, WHITE},
    {64.85f, TAP, Shipping::RIGHT, WHITE},
    {65.27f, TAP, Shipping::RIGHT, WHITE},
    {65.69f, TAP, Shipping::LEFT, WHITE},
    {66.52f, TAP, Shipping::RIGHT, WHITE},
    {66.94f, TAP, Shipping::LEFT, WHITE},
    {67.77f, TAP, Shipping::LEFT, WHITE},
    {68.19f, TAP, Shipping::RIGHT, WHITE},
    {68.61f, TAP, Shipping::LEFT, WHITE},
    {69.44f, HOLD, Shipping::RIGHT, WHITE, {400, 50}},
    {69.86f, TAP, Shipping::LEFT, WHITE},
    {70.69f, TAP, Shipping::LEFT, WHITE},
    {71.11f, TAP, Shipping::RIGHT, WHITE},
    {71.53f, TAP, Shipping::LEFT, WHITE},
    {72.36f, HOLD, Shipping::LEFT, WHITE, {400, 50}},
    {72.78f, TAP, Shipping::RIGHT, WHITE},
    {73.61f, TAP, Shipping::RIGHT, WHITE},
    {74.03f, TAP, Shipping::RIGHT, WHITE},
    {75.2f, HOLD, Shipping::LEFT, WHITE, {400, 50}},
    {75.2f, HOLD, Shipping::RIGHT, WHITE, {400, 50}},
    {80.29f, TAP, Shipping::RIGHT, WHITE},
    {80.29f, TAP, Shipping::LEFT, WHITE},
};

std::vector<ScheduleNote> noteSchedule;

void ResetSchedule()
{
    noteSchedule.clear();
    noteSchedule = baseNoteSchedule;
}